/** 领域层导出入口。 约束：仅包含共享契约、类型与纯函数；禁止执行业务 I/O （不得读写磁盘、发起网络请求、访问 Docker 或环境副作用业务逻辑）。 */
export const DOMAIN_PACKAGE_NAME = "@homepage/domain" as const;

export const DOMAIN_BOUNDARY = {
  packageName: DOMAIN_PACKAGE_NAME,
  allowsBusinessIo: false,
  role: "shared-contracts-and-pure-functions",
} as const;

export {
  API_ERROR_STATUS_BY_CODE,
  API_JSON_CONTENT_TYPE,
  ApiErrorCode,
  ApiHttpStatus,
  ApiRoutes,
  ApiSuccessMeta,
  ApiSuccessSchemas,
  AssetUploadSuccessResponseSchema,
  IconCandidateSchema,
  IconImportSuccessResponseSchema,
  IconResolveSuccessResponseSchema,
  SiteIconTierSchema,
  BookmarkGroupItemSchema,
  BookmarkGroupSchema,
  BookmarkItemErrorSchema,
  ConfigSuccessResponseSchema,
  ConfigWriteSuccessResponseSchema,
  DockerBatchItemSchema,
  DockerBatchStatusResponseSchema,
  DockerBatchSuccessResponseSchema,
  DockerContainerSummarySchema,
  DockerContainersResponseSchema,
  DockerContainersSuccessResponseSchema,
  DockerHealthSchema,
  DockerResourceStatsSchema,
  DockerStateSchema,
  DockerStatusResponseSchema,
  DockerSuccessResponseSchema,
  EditableBookmarkGroupSchema,
  EditableBookmarkItemSchema,
  EditableConfigSchema,
  EditableConfigSuccessResponseSchema,
  EditableConfigWriteSchema,
  EditableDatetimeInfoSchema,
  EditableDiskEntrySchema,
  EditableDiskFieldSchema,
  EditableDockerEndpointSchema,
  EditableHttpProbeSchema,
  EditableInfoWidgetSchema,
  EditableLayoutEntrySchema,
  EditableOpenMeteoInfoSchema,
  EditableResourcesInfoSchema,
  EditableServiceDockerSchema,
  EditableServiceGroupViewSchema,
  EditableServiceGroupWriteSchema,
  EditableServiceItemViewSchema,
  EditableServiceItemWriteSchema,
  EditableServiceWidgetViewSchema,
  EditableServiceWidgetWriteSchema,
  EditableSettingsSchema,
  EmbySessionSummarySchema,
  ErrorEnvelopeSchema,
  HttpProbeResponseSchema,
  HttpProbeStateSchema,
  HttpUnreachableReasonSchema,
  InfoSuccessResponseSchema,
  InfoWidgetConfigSchema,
  InfoWidgetTypeSchema,
  LayoutGroupSchema,
  MetricSchema,
  MetricStatusSchema,
  NormalizedBookmarkSchema,
  NormalizedConfigSchema,
  NormalizedServiceSchema,
  NormalizedSettingsSchema,
  OpenMeteoInfoResponseSchema,
  WeatherDailyItemSchema,
  WeatherHourlyItemSchema,
  ProbeSuccessResponseSchema,
  PublicErrorSchema,
  ResourceAvailableItemSchema,
  ResourceItemSchema,
  ResourceUnavailableItemSchema,
  ResourcesInfoResponseSchema,
  SecretFieldViewSchema,
  SecretFieldWriteSchema,
  ServiceDockerRefSchema,
  ServiceGroupItemSchema,
  ServiceGroupSchema,
  ServiceHttpProbeSchema,
  ServiceItemErrorSchema,
  ServiceWidgetOkResponseSchema,
  ServiceWidgetRefSchema,
  ServiceWidgetResultSchema,
  ServiceWidgetTypeSchema,
  StatusRangeSchema,
  VersionSuccessResponseSchema,
  WidgetSuccessResponseSchema,
  createApiError,
  createApiNotFoundError,
  createConfigFaultedApiError,
  createConfigInvalidError,
  createDockerConnectionSensitiveApiError,
  createErrorEnvelope,
  createExternalFailureError,
  createExternalTimeoutError,
  createForbiddenError,
  createInternalError,
  createPublicError,
  isApiPath,
  parseApiSuccess,
  parseErrorEnvelope,
  resolveApiErrorStatus,
  type ApiErrorCodeValue,
  type ApiErrorResponse,
  type ApiHttpStatusCode,
  type ApiRouteKey,
  type ApiSuccessRoute,
  type AssetUploadSuccessResponse,
  type IconCandidate,
  type IconImportSuccessResponse,
  type IconResolveSuccessResponse,
  type SiteIconTierContract,
  type VersionSuccessResponse,
  type BookmarkGroup,
  type BookmarkGroupItem,
  type BookmarkItemError,
  type ConfigSuccessResponse,
  type ConfigWriteSuccessResponse,
  type CreateApiErrorOptions,
  type CreatePublicErrorInput,
  type DockerBatchItem,
  type DockerBatchStatusResponse,
  type DockerBatchSuccessResponse,
  type DockerContainerSummary,
  type DockerContainersResponse,
  type DockerContainersSuccessResponse,
  type DockerHealth,
  type DockerResourceStats,
  type DockerState,
  type DockerStatusResponse,
  type DockerSuccessResponse,
  type EditableBookmarkGroup,
  type EditableBookmarkItem,
  type EditableConfig,
  type EditableConfigSuccessResponse,
  type EditableConfigWrite,
  type EditableDiskEntry,
  type EditableDiskField,
  type EditableDockerEndpoint,
  type EditableHttpProbe,
  type EditableInfoWidget,
  type EditableLayoutEntry,
  type EditableServiceDocker,
  type EditableServiceGroupView,
  type EditableServiceGroupWrite,
  type EditableServiceItemView,
  type EditableServiceItemWrite,
  type EditableServiceWidgetView,
  type EditableServiceWidgetWrite,
  type EditableSettings,
  type EmbySessionSummary,
  type ErrorEnvelope,
  type HttpProbeResponse,
  type HttpProbeState,
  type HttpUnreachableReason,
  type InfoSuccessResponse,
  type InfoWidgetConfig,
  type InfoWidgetType,
  type LayoutGroup,
  type Metric,
  type MetricStatus,
  type NormalizedBookmark,
  type NormalizedConfig,
  type NormalizedService,
  type NormalizedSettings,
  type OpenMeteoInfoResponse,
  type WeatherDailyItem,
  type WeatherHourlyItem,
  type ProbeSuccessResponse,
  type PublicError,
  type ResourceAvailableItem,
  type ResourceItem,
  type ResourceUnavailableItem,
  type ResourcesInfoResponse,
  type SecretFieldView,
  type SecretFieldWrite,
  type ServiceDockerRef,
  type ServiceGroup,
  type ServiceGroupItem,
  type ServiceHttpProbe,
  type ServiceItemError,
  type ServiceWidgetOkResponse,
  type ServiceWidgetRef,
  type ServiceWidgetResult,
  type ServiceWidgetType,
  type StatusRange,
  type WidgetSuccessResponse,
} from "./contracts/index.js";

export {
  CANONICAL_FIELD_SEP,
  CANONICAL_VERSION,
  STABLE_ID_HASH_HEX_LENGTH,
  STABLE_ID_PREFIX,
  assignStableIdsFromFixture,
  buildInfoCanonical,
  buildInfoId,
  buildProbeCanonical,
  buildProbeId,
  buildServiceCanonical,
  buildServiceId,
  buildStableId,
  buildWidgetCanonical,
  buildWidgetId,
  collectPublicIdSurfaces,
  findMissedAllowListIdsFromResults,
  joinCanonicalParts,
  normalizeAbsoluteHttpUrl,
  normalizeDiskPathIdentity,
  normalizeDiskPathSet,
  normalizeTypeToken,
  serializeFourIdSets,
  sha256Hex,
  type BuildInfoIdInput,
  type BuildProbeIdInput,
  type BuildServiceIdInput,
  type BuildWidgetIdInput,
  type EmptyTargetIdentity,
  type FixtureInfoWidget,
  type FixtureServiceItem,
  type FixtureServiceWidget,
  type FourIdSets,
  type IdAssignmentFixture,
  type IdAssignmentResult,
  type InfoAllowEntry,
  type InfoCanonicalInput,
  type InfoTargetIdentity,
  type OpenMeteoTargetIdentity,
  type ProbeAllowEntry,
  type ProbeCanonicalInput,
  type ResourcesTargetIdentity,
  type ServiceCanonicalInput,
  type SimulatedAllowList,
  type StableIdKind,
  type WidgetAllowEntry,
  type WidgetCanonicalInput,
} from "./ids/index.js";

export {
  BOOKMARK_MIN_ITEM_WIDTH_PX,
  DEFAULT_DASHBOARD_TITLE,
  SERVICE_MIN_ITEM_WIDTH_PX,
  WHOLE_ENV_PLACEHOLDER_RE,
  clampPercent,
  classifyHttpProbe,
  interpolateEnvWholeValue,
  isAbsoluteHttpUrl,
  isValidDockerState,
  isValidHttpProbeState,
  isWholeEnvPlaceholder,
  matchSearch,
  matchesExpected,
  normalizeExpectedStatus,
  normalizeTitle,
  parseThemeMode,
  resolveBookmarkIconFallback,
  resolveColumns,
  sortServicesStable,
  bytesToDataUrl,
  detectImageExtension,
  discoverIconRefsFromHtml,
  isHttpOrHttpsUrl,
  isSameHost,
  mergeIconDiscovery,
  mimeTypeForImageExt,
  resolveMaybeRelativeUrl,
  staticIconFallbackRefs,
  type BookmarkIconFallbackInput,
  type BookmarkIconFallbackResult,
  type DiscoveredIconRef,
  type ImageExt,
  type InterpolateEnvResult,
  type NetworkProbeResult,
  type ResolvedTheme,
  type SearchableItem,
  type SiteIconTier,
  type ThemeMode,
  type Weightable,
} from "./pure/index.js";

